"""
CLASSES
"""
CLASSES = [
    {
        "id": "cleric",
        "name": "Cleric",
        "name_colored": "{RC{rleric",
        "name_short_colored": "{RC{rle",
        "tier": 1,
    },
    {
        "id": "druid",
        "name": "Druid",
        "name_colored": "{RD{rruid",
        "name_short_colored": "{RD{rru",
        "tier": 1,
    },
    {
        "id": "mage",
        "name": "Mage",
        "name_colored": "{RM{rage",
        "name_short_colored": "{RM{rag",
        "tier": 1,
    },
    {
        "id": "ranger",
        "name": "Ranger",
        "name_colored": "{RR{ranger",
        "name_short_colored": "{RR{ran",
        "tier": 1,
    },
    {
        "id": "thief",
        "name": "Thief",
        "name_colored": "{RT{rhief",
        "name_short_colored": "{RT{rhi",
        "tier": 1,
    },
    {
        "id": "warrior",
        "name": "Warrior",
        "name_colored": "{RW{rarrior",
        "name_short_colored": "{RW{rar",
        "tier": 1,
    },
    {
        "id": "vampire",
        "name": "Vampire",
        "name_colored": "{RV{rampire",
        "name_short_colored": "{RV{ram",
        "tier": 1,
    },
    {
        "id": "priest",
        "name": "Priest",
        "name_colored": "{BP{briest",
        "name_short_colored": "{BP{bri",
        "tier": 2,
        "parent_class_id": "cleric",
    },
    {
        "id": "sage",
        "name": "Sage",
        "name_colored": "{BS{bage",
        "name_short_colored": "{BS{bag",
        "tier": 2,
        "parent_class_id": "druid",
    },
    {
        "id": "wizard",
        "name": "Wizard",
        "name_colored": "{BW{bizard",
        "name_short_colored": "{BW{biz",
        "tier": 2,
        "parent_class_id": "mage",
    },
    {
        "id": "strider",
        "name": "Strider",
        "name_colored": "{BS{btrider",
        "name_short_colored": "{BS{btr",
        "tier": 2,
        "parent_class_id": "ranger",
    },
    {
        "id": "mercenary",
        "name": "Mercenary",
        "name_colored": "{BM{bercenary",
        "name_short_colored": "{BM{ber",
        "tier": 2,
        "parent_class_id": "thief",
    },
    {
        "id": "glariator",
        "name": "Glariator",
        "name_colored": "{BG{bladiator",
        "name_short_colored": "{BG{bla",
        "tier": 2,
        "parent_class_id": "warrior",
    },
    {
        "id": "lich",
        "name": "Lich",
        "name_colored": "{BL{bich",
        "name_short_colored": "{BL{bic",
        "tier": 2,
        "parent_class_id": "vampire",
    },
]
