"""
RACES
"""
RACES = [
    {
        "id": "human",
        "name": "Human",
        "name_colored": "{CH{cuman",
    },
    {
        "id": "drow",
        "name": "Drow",
        "name_colored": "{CD{crow",
        "resists": [],
        "vulns": ["holy"],
    },
    {
        "id": "pixie",
        "name": "Pixie",
        "name_colored": "{CP{cixie",
        "resists": [],
        "vulns": [],
    },
    {
        "id": "halfling",
        "name": "Halfling",
        "name_colored": "{CH{cflng",
        "resists": [],
        "vulns": [],
    },
    {
        "id": "goblin",
        "name": "Goblin",
        "name_colored": "{CG{cobln",
        "resists": [],
        "vulns": [],
    },
    {
        "id": "gnome",
        "name": "Gnome",
        "name_colored": "{CG{cnome",
        "resists": [],
        "vulns": [],
    },
    {
        "id": "kenku",
        "name": "Kenku",
        "name_colored": "{CK{cenku",
        "resists": [],
        "vulns": [],
    },
    {
        "id": "satyr",
        "name": "Satyr",
        "name_colored": "{CS{catyr",
        "resists": [],
        "vulns": [],
    },
    {
        "id": "podriken",
        "name": "Podrikev",
        "name_colored": "{CP{codkv",
        "resists": [],
        "vulns": [],
    },
    {
        "id": "avian",
        "name": "Avian",
        "name_colored": "{CA{cvian",
        "resists": [],
        "vulns": [],
    },
    {
        "id": "draconian",
        "name": "Draconian",
        "name_colored": "{CD{cracn",
        "resists": [],
        "vulns": [],
    },
    {
        "id": "thrikreen",
        "name": "Thri'Kreen",
        "name_colored": "{CT{chrik",
        "resists": [],
        "vulns": [],
    },
    {
        "id": "elf",
        "name": "Elf",
        "name_colored": "{CE{clf",
        "resists": [],
        "vulns": [],
    },
    {
        "id": "dwarf",
        "name": "Dwarf",
        "name_colored": "{CD{cwarf",
        "resists": [],
        "vulns": [],
    },
    {
        "id": "esper",
        "name": "Esper",
        "name_colored": "{CE{csper",
        "resists": [],
        "vulns": [],
    },
    {
        "id": "halforc",
        "name": "Half Orc",
        "name_colored": "{CH{c.Orc",
        "resists": [],
        "vulns": [],
    },
    {
        "id": "halfelf",
        "name": "Half Elf",
        "name_colored": "{CH{c.Elf",
        "resists": [],
        "vulns": [],
    },
    {
        "id": "gnoll",
        "name": "Gnoll",
        "name_colored": "{CG{cnoll",
        "resists": [],
        "vulns": [],
    },
    {
        "id": "minotaur",
        "name": "Minotaur",
        "name_colored": "{CM{cintr",
        "resists": [],
        "vulns": [],
    },
    {
        "id": "titan",
        "name": "Titan",
        "name_colored": "{CT{citan",
        "resists": [],
        "vulns": [],
    },
    {
        "id": "giant",
        "name": "Giant",
        "name_colored": "{CG{ciant",
        "resists": [],
        "vulns": [],
    },
    {
        "id": "heucuva",
        "name": "Heucuva",
        "name_colored": "{CH{ceucv",
        "resists": [],
        "vulns": [],
    },
    {
        "id": "centaur",
        "name": "Centaur",
        "name_colored": "{CC{centr",
        "resists": [],
        "vulns": [],
    },
    {
        "id": "troll",
        "name": "TRoll",
        "name_colored": "{CT{croll",
        "resists": [],
        "vulns": [],
    },
]
